import os, platform

Import('env')
env_test = env.Clone()

if(platform.system() == "Linux"):
   env_test.Replace( LIBS = [ 'boost_unit_test_framework' ] )
else:
   print platform.system() + " not supported"
   
# build C++ test program
test_build = env_test.Program(target = 'tests', source = ['tests.cpp'])
